// Generated by CodiumAI

describe('restrictToWhom_function', () => {

});

    // Tests that the middleware rejects unauthenticated users
    it('test_rejects_unauthenticated_users', () => {
        const req = { user: null };
        const res = { redirect: jest.fn(), end: jest.fn() };
        const next = jest.fn();

        restrictToWhom(['admin'])(req, res, next);

        expect(res.redirect).toHaveBeenCalledWith('/login');
        expect(res.end).not.toHaveBeenCalled();
        expect(next).not.toHaveBeenCalled();
    });

